"use client";

const calculatorImports: Record<string, () => Promise<any>> = {
  "basic": () => import("@/calculators/basic").then(m => m.basic),
  "percentage": () => import("@/calculators/percentage").then(m => m.percentage),
  "fraction-simplifier": () => import("@/calculators/fraction-simplifier").then(m => m.fractionSimplifier),
  "average-stats": () => import("@/calculators/average-stats").then(m => m.averageStats),
  "unit-price": () => import("@/calculators/unit-price").then(m => m.unitPrice),
  "ratio-proportion": () => import("@/calculators/ratio-proportion").then(m => m.ratioProportion),
  "gcd-lcm": () => import("@/calculators/gcd-lcm").then(m => m.gcdLcm),
  "rounding": () => import("@/calculators/rounding").then(m => m.rounding),
  "prime-check": () => import("@/calculators/prime-check").then(m => m.primeCheck),
  "area-circle": () => import("@/calculators/area-circle").then(m => m.areaCircle),
  "area-rectangle": () => import("@/calculators/area-rectangle").then(m => m.areaRectangle),
  "power-root": () => import("@/calculators/power-root").then(m => m.powerRoot),
  "tip": () => import("@/calculators/tip").then(m => m.tip),
  "sales-tax": () => import("@/calculators/sales-tax").then(m => m.salesTax),
  "loan": () => import("@/calculators/loan").then(m => m.loan),
  "mortgage": () => import("@/calculators/mortgage").then(m => m.mortgage),
  "compound-interest": () => import("@/calculators/compound-interest").then(m => m.compoundInterest),
  "simple-interest": () => import("@/calculators/simple-interest").then(m => m.simpleInterest),
  "roi": () => import("@/calculators/roi").then(m => m.roi),
  "margin-markup": () => import("@/calculators/margin-markup").then(m => m.marginMarkup),
  "apr-to-apy": () => import("@/calculators/apr-to-apy").then(m => m.aprToApy),
  "present-value": () => import("@/calculators/present-value").then(m => m.presentValue),
  "future-value": () => import("@/calculators/future-value").then(m => m.futureValue),
  "credit-card-payoff": () => import("@/calculators/credit-card-payoff").then(m => m.creditCardPayoff),
  "break-even": () => import("@/calculators/break-even").then(m => m.breakEven),
  "bmi": () => import("@/calculators/bmi").then(m => m.bmi),
  "bmr-tdee": () => import("@/calculators/bmr-tdee").then(m => m.bmrTdee),
  "macros": () => import("@/calculators/macros").then(m => m.macros),
  "heart-rate-zones": () => import("@/calculators/heart-rate-zones").then(m => m.heartRateZones),
  "water-intake": () => import("@/calculators/water-intake").then(m => m.waterIntake),
  "body-fat-navy": () => import("@/calculators/body-fat-navy").then(m => m.bodyFatNavy),
  "running-pace": () => import("@/calculators/running-pace").then(m => m.runningPace),
  "calories-met": () => import("@/calculators/calories-met").then(m => m.caloriesMet),
  "one-rep-max": () => import("@/calculators/one-rep-max").then(m => m.oneRepMax),
  "temp-convert": () => import("@/calculators/temp-convert").then(m => m.tempConvert),
  "length-convert": () => import("@/calculators/length-convert").then(m => m.lengthConvert),
  "mass-convert": () => import("@/calculators/mass-convert").then(m => m.massConvert),
  "speed-convert": () => import("@/calculators/speed-convert").then(m => m.speedConvert),
  "pressure-convert": () => import("@/calculators/pressure-convert").then(m => m.pressureConvert),
  "volume-convert": () => import("@/calculators/volume-convert").then(m => m.volumeConvert),
  "energy-convert": () => import("@/calculators/energy-convert").then(m => m.energyConvert),
  "angle-deg-rad": () => import("@/calculators/angle-deg-rad").then(m => m.angleDegRad),
  "ohms-law": () => import("@/calculators/ohms-law").then(m => m.ohmsLaw),
  "resistor-divider": () => import("@/calculators/resistor-divider").then(m => m.resistorDivider),
  "led-resistor": () => import("@/calculators/led-resistor").then(m => m.ledResistor),
  "rc-cutoff": () => import("@/calculators/rc-cutoff").then(m => m.rcCutoff),
  "capacitor-charge": () => import("@/calculators/capacitor-charge").then(m => m.capacitorCharge),
  "battery-runtime": () => import("@/calculators/battery-runtime").then(m => m.batteryRuntime),
  "date-diff": () => import("@/calculators/date-diff").then(m => m.dateDiff),
  "epoch-converter": () => import("@/calculators/epoch-converter").then(m => m.epochConverter),
};

export function loadCalculator(slug: string): Promise<any> {
  const importer = calculatorImports[slug];
  if (!importer) return Promise.resolve(null);
  return importer().catch(() => null);
}