"use client";

const calculatorImports: Record<string, () => Promise<any>> = {
  "alcohol-units": () => import("@/calculators/alcohol-units").then(m => m.alcoholUnits),
  "angle-deg-rad": () => import("@/calculators/angle-deg-rad").then(m => m.angleDegRad),
  "annuity": () => import("@/calculators/annuity").then(m => m.annuity),
  "apr-to-apy": () => import("@/calculators/apr-to-apy").then(m => m.aprToApy),
  "area-circle": () => import("@/calculators/area-circle").then(m => m.areaCircle),
  "area-rectangle": () => import("@/calculators/area-rectangle").then(m => m.areaRectangle),
  "average-stats": () => import("@/calculators/average-stats").then(m => m.averageStats),
  "basic": () => import("@/calculators/basic").then(m => m.basic),
  "battery-runtime": () => import("@/calculators/battery-runtime").then(m => m.batteryRuntime),
  "bmi": () => import("@/calculators/bmi").then(m => m.bmi),
  "bmr-tdee": () => import("@/calculators/bmr-tdee").then(m => m.bmrTdee),
  "body-fat-percentage": () => import("@/calculators/body-fat-percentage").then(m => m.bodyFatNavy2),
  "break-even": () => import("@/calculators/break-even").then(m => m.breakEven),
  "bsa": () => import("@/calculators/bsa").then(m => m.bsa),
  "calories-met": () => import("@/calculators/calories-met").then(m => m.caloriesMet),
  "capacitor-charge": () => import("@/calculators/capacitor-charge").then(m => m.capacitorCharge),
  "compound-interest": () => import("@/calculators/compound-interest").then(m => m.compoundInterest),
  "credit-card-payoff": () => import("@/calculators/credit-card-payoff").then(m => m.creditCardPayoff),
  "currency-converter": () => import("@/calculators/currency-converter").then(m => m.currencyConverter),
  "date-calculator": () => import("@/calculators/date-calculator").then(m => m.dateCalculator),
  "date-diff": () => import("@/calculators/date-diff").then(m => m.dateDiff),
  "debt-payoff": () => import("@/calculators/debt-payoff").then(m => m.debtPayoff),
  "dollar-cost-averaging": () => import("@/calculators/dollar-cost-averaging").then(m => m.dollarCostAveraging),
  "emergency-fund": () => import("@/calculators/emergency-fund").then(m => m.emergencyFund),
  "energy-convert": () => import("@/calculators/energy-convert").then(m => m.energyConvert),
  "epoch-converter": () => import("@/calculators/epoch-converter").then(m => m.epochConverter),
  "fire-calculator": () => import("@/calculators/fire-calculator").then(m => m.fireCalculator),
  "fraction-simplifier": () => import("@/calculators/fraction-simplifier").then(m => m.fractionSimplifier),
  "fuel-cost": () => import("@/calculators/fuel-cost").then(m => m.fuelCost),
  "future-value": () => import("@/calculators/future-value").then(m => m.futureValue),
  "gcd-lcm": () => import("@/calculators/gcd-lcm").then(m => m.gcdLcm),
  "heart-rate-zones": () => import("@/calculators/heart-rate-zones").then(m => m.heartRateZones),
  "inflation-calculator": () => import("@/calculators/inflation-calculator").then(m => m.inflationCalculator),
  "led-resistor": () => import("@/calculators/led-resistor").then(m => m.ledResistor),
  "length-convert": () => import("@/calculators/length-convert").then(m => m.lengthConvert),
  "loan": () => import("@/calculators/loan").then(m => m.loan),
  "loan-amortization": () => import("@/calculators/loan-amortization").then(m => m.loanAmortization),
  "macro-calculator-advanced": () => import("@/calculators/macro-calculator-advanced").then(m => m.macrosCalculator2),
  "margin-markup": () => import("@/calculators/margin-markup").then(m => m.marginMarkup),
  "mass-convert": () => import("@/calculators/mass-convert").then(m => m.massConvert),
  "mortgage": () => import("@/calculators/mortgage").then(m => m.mortgage),
  "mortgage-refinance": () => import("@/calculators/mortgage-refinance").then(m => m.mortgageRefinance),
  "ohms-law": () => import("@/calculators/ohms-law").then(m => m.ohmsLaw),
  "one-rep-max": () => import("@/calculators/one-rep-max").then(m => m.oneRepMax),
  "percentage": () => import("@/calculators/percentage").then(m => m.percentage),
  "power-root": () => import("@/calculators/power-root").then(m => m.powerRoot),
  "present-value": () => import("@/calculators/present-value").then(m => m.presentValue),
  "pressure-convert": () => import("@/calculators/pressure-convert").then(m => m.pressureConvert),
  "prime-check": () => import("@/calculators/prime-check").then(m => m.primeCheck),
  "protein-intake": () => import("@/calculators/protein-intake").then(m => m.proteinIntake),
  "ratio-proportion": () => import("@/calculators/ratio-proportion").then(m => m.ratioProportion),
  "rc-cutoff": () => import("@/calculators/rc-cutoff").then(m => m.rcCutoff),
  "rental-yield": () => import("@/calculators/rental-yield").then(m => m.rentalYield),
  "resistor-divider": () => import("@/calculators/resistor-divider").then(m => m.resistorDivider),
  "retirement-age": () => import("@/calculators/retirement-age").then(m => m.retirementAge),
  "retirement-withdrawal": () => import("@/calculators/retirement-withdrawal").then(m => m.retirementWithdrawal),
  "roi": () => import("@/calculators/roi").then(m => m.roi),
  "rounding": () => import("@/calculators/rounding").then(m => m.rounding),
  "rule-of-72": () => import("@/calculators/rule-of-72").then(m => m.ruleOf72),
  "running-pace": () => import("@/calculators/running-pace").then(m => m.runningPace),
  "salary-comparison": () => import("@/calculators/salary-comparison").then(m => m.salaryComparison),
  "savings-goal": () => import("@/calculators/savings-goal").then(m => m.savingsGoal),
  "simple-interest": () => import("@/calculators/simple-interest").then(m => m.simpleInterest),
  "social-security": () => import("@/calculators/social-security").then(m => m.socialSecurity),
  "speed-convert": () => import("@/calculators/speed-convert").then(m => m.speedConvert),
  "stock-options": () => import("@/calculators/stock-options").then(m => m.stockOptions),
  "tax-bracket": () => import("@/calculators/tax-bracket").then(m => m.taxBracket),
  "temp-convert": () => import("@/calculators/temp-convert").then(m => m.tempConvert),
  "tip": () => import("@/calculators/tip").then(m => m.tip),
  "tire-size": () => import("@/calculators/tire-size").then(m => m.tireSize),
  "torque-converter": () => import("@/calculators/torque-converter").then(m => m.torqueConverter),
  "unit-price": () => import("@/calculators/unit-price").then(m => m.unitPrice),
  "vat-calculator": () => import("@/calculators/vat-calculator").then(m => m.vatCalculator),
  "volume-convert": () => import("@/calculators/volume-convert").then(m => m.volumeConvert),
  "water-intake": () => import("@/calculators/water-intake").then(m => m.waterIntake),
  "workout-volume": () => import("@/calculators/workout-volume").then(m => m.workoutVolume),
};

export function loadCalculator(slug: string): Promise<any> {
  const importer = calculatorImports[slug];
  if (!importer) return Promise.resolve(null);
  return importer().catch(() => null);
}
